# Generated by Django 5.2.4 on 2025-07-28 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shorturl",
            old_name="shortcode",
            new_name="short_code",
        ),
        migrations.RemoveField(
            model_name="shorturl",
            name="click_count",
        ),
        migrations.RemoveField(
            model_name="shorturl",
            name="expires_at",
        ),
        migrations.DeleteModel(
            name="ClickStats",
        ),
    ]
