# Generated by Django 5.2.4 on 2025-07-28 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0002_rename_shortcode_shorturl_short_code_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ShortURL",
            new_name="ShortenedURL",
        ),
    ]
