# Generated by Django 5.2.4 on 2025-07-28 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0003_rename_shorturl_shortenedurl"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ShortenedURL",
            new_name="ShortURL",
        ),
    ]
